### ISSUE TITLE
Add a cursor to the CSS.

### ISSUE THREAD

**Issue by SonJimin** [junhoyeo/Comgong-Bingo#2]
안녕하세요 😄
컴공 빙고를 살펴보다가 추가했으면 하는 점이 있어서 남기려고 합니다 🤔

**1 ) button.btn**
     
![image](https://user-images.githubusercontent.com/47082043/52166728-429f8f00-2754-11e9-9d43-1e921a539f86.png)

버튼 부분에서 '**cursor**'를 지정하지 않아 버튼을 클릭하였다는 
부분이 존재하지 않는 걸 확인했습니다. 
해결하기 위해선 ' **cursor: pointer** '를 button.btn에 추가해주시면 좋을 거 같습니다.

**Comment by junhoyeo** [comment]
감사합니다! 다음 커밋 때 추가하겠습니다 :D

**Comment by junhoyeo** [comment]
Fixed on commit 8c32e9f63c9fc4f28732159b525fda888af57bc5
